spring.application.name=smartshop

spring.datasource.url=jdbc:postgresql://localhost:5432/smartshop_db
spring.datasource.username=postgres
spring.datasource.password=MhamedOuhanane@1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

spring.jackson.deserialization.fail-on-unknown-properties=false

spring.mvc.throw-exception-if-no-handler-found=true

spring.port=8080