spring.datasource.url=jdbc:postgresql://postgres:5432/smartshop
spring.datasource.username=smartshop
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
